### ISSUE TITLE
[Feature request] Option to convert results to an EDL segment

### ISSUE THREAD

**Issue by norveganon** [linguisticmind/search-in-subs#2]
Hi and thanks for the script. It got me thinking about your ab-loop-to-edl-segment script. I don't know how difficult this would be to implement, but it would be really cool to have an option to convert the results to an EDL segment, but instead of converting a loop region as you do with your ab-loop scripts, the subtitle regions that match the search would be converted. That way you can basically watch the results by playing the EDL file.

With this feature, how easy would it by to put together something like [this](https://www.youtube.com/watch?v=Wko79qs9_us)?

I imagine it would go something like this:
1. Search the f-word using this search-in-subs script with the option to convert results to EDL segment.
2. Play EDL file.
3. Clean up the cuts using your ab-loop scripts.

Thoughts?

**Comment by linguisticmind** [comment]
Thanks for the feature request! I had a similar idea myself, so I went ahead and implemented it. The script has been updated to v0.2.0, and here's a video where I demonstrate how everything works: https://youtu.be/M81f6GrqRS4

Hope you like this new feature. I've also recorded some live coding videos documenting most of the implementation process, and I'll be releasing those on [the channel](https://www.youtube.com/channel/UCi0KOqT1BBKcfWMV_s9-F5w/) shortly as well.

**Comment by norveganon** [comment]
Great job!

It'd be convenient to have an option to save the results as separate video files as well. So if you get 5 hits on a search, it saves them to 5 separate video clips. That would make it easy to bring into a video editing software for further editing.

I imagine it'd be a ffmpeg command using the -ss, -to and -c copy options for each hit or something like that?

**Comment by linguisticmind** [comment]
mpv actually has a video encoding functionality, (see [ENCODING section in the manual](https://mpv.io/manual/stable/#encoding)), so it might come in handy when it comes to rendering EDLs into video. I'm not sure how to split it into search results, though. We do have chapters for each search result, so that can be used to get the timecodes.

I had an idea similar to this one. Kdenlive's project files are plain text XML files. So it is probably possible to convert mpv EDLs to Kdenlive projects. This would avoid the unnecessary quality loss due to encoding each clip separately before importing them into a video editing software. The video data would come directly from the source files.

**Comment by norveganon** [comment]
The -c copy option in ffmpeg just copies out the streams without reencoding. I made a little script to test it out. It's a bit of a roundabout way of doing it, but I generate an edl file with the -f option and then run this script on it:

```
#!/bin/bash

edl_file="$1"

while read line; do
    if [[ "$line" =~ ^#.*$ ]] || [[ -z "$line" ]]; then
        continue
    fi

    video_file="$(echo "$line" | cut -d',' -f1)"
    video_file="${video_file#*[0-9]%}"
    start_time="$(echo "$line" | cut -d',' -f2)"
    duration="$(echo "$line" | cut -d',' -f3)"

    # round start time and duration to three decimals
    start_time=$(printf "%.3f" "$start_time")
    duration=$(printf "%.3f" "$duration")

    echo "Video File: $video_file"
    echo "Start Time: $start_time"
    echo "Duration: $duration"

   {
    ffmpeg \
        -hide_banner \
        -i "$video_file" \
        -ss "$start_time" \
        -t "$duration" \
        -c copy \
        "${video_file%.*}_clip_${start_time}_dur_${duration}.${video_file##*.}"
   } &

done < "$edl_file"
```

There are some issues with it, it doesn't like when the segments are too short, there might be some ffmpeg options to remedy this, but adding some time with the -a and -b options when generating the edl file helps. And for some reason I have to run the ffmpeg command in a sub process or one of the segments isn't made into a clip, not sure why that is, I'm no expert. But anyway, the idea is to have an option that just does something like this in the script, that way you can extract the short clips you want from all the seasons of game of thrones, and then delete the full episodes afterwards, you know? But no worries if you can't be bothered looking into it.

**Comment by linguisticmind** [comment]
Also, relevant to this thread:

I've now written a tool called [ezedl](https://github.com/linguisticmind/ezedl) that can help with adjusting time for individual segments in the generated EDL files.

**Comment by norveganon** [comment]
Nice, that might come in handy, tharks!

Btw, I tried to the -s option in search-in-subs and it was complained about the --zero option used in ls on this line:
`mapfile -d '' stats_files_quoted < <(ls --zero --sort=none --quoting-style=shell-escape --color=never "$@")`
My ls doesn't have a --zero option.

ls has a loose, non-standard format and may "clean up" filenames to make output easier to read as it's mainly intended for human consumption, it works most of the time, but sometimes it has [unintended](https://yt.cdaut.de/watch?v=PEKNB5ex29U) [results](https://yt.cdaut.de/watch?v=A-UFX6bpQzM) when used in scripts, so it's probably better to find another solution to make it more robust.

**Comment by linguisticmind** [comment]
Thanks for reporting. I opened a [new issue](https://github.com/linguisticmind/search-in-subs/issues/3) for this, and I'll comment on it there.
