### ISSUE TITLE
ls not having --zero when using -s, --stats

### ISSUE THREAD

**Issue by linguisticmind** [linguisticmind/search-in-subs#3]
> Btw, I tried to the -s option in search-in-subs and it was complained about the --zero option used in ls on this line:
`mapfile -d '' stats_files_quoted < <(ls --zero --sort=none --quoting-style=shell-escape --color=never "$@")`
My ls doesn't have a --zero option.
>
> ls has a loose, non-standard format and may "clean up" filenames to make output easier to read as it's mainly intended for human consumption, it works most of the time, but sometimes it has [unintended](https://yt.cdaut.de/watch?v=PEKNB5ex29U) [results](https://yt.cdaut.de/watch?v=A-UFX6bpQzM) when used in scripts, so it's probably better to find another solution to make it more robust.

_Originally posted by @norveganon in https://github.com/linguisticmind/search-in-subs/issues/2#issuecomment-2112059879_

**Comment by linguisticmind** [comment]
Thanks for reporting. Yeah, this is a valid point, and I think I know how to improve this.

But first I wanted to say that to remedy this, you might want to install GNU Coreutils. They have a lot of useful extensions in their implementation of coreutils, and this `--zero` option for `ls` must be one of them. I don't know what system you're on, but in case you (or someone else reading this) are on a Mac, you might find [this old tutorial of mine](https://youtu.be/vC6ykcyTzLg) on the MacPorts and Homebrew package managers helpful. The package name for GNU Coreutils is `coreutils` on both of those package managers. GNU sed is also good to have (`gsed` on MacPorts/Homebrew).

But in any case, I've recently [found a better way of quoting strings in Bash scripts for displaying them in messages](https://youtu.be/_DnwyyDOvhc). I only recently found out about this handy `parameter@operator` expansion. It can do many things, but if you do `${parameter@Q}`, it produces a correctly quoted string. It is definitely better than using `ls`, or my previous semi-working Bash-only solution of doing `\'"${parameter//\'/\'\\\'\'}"\'` which is okay most of the time, but not if the value contains unusual characters like newlines, tabs, carriage returns etc.

So I'll try to incorporate this new way of quoting strings into this script when time permits.

**Comment by norveganon** [comment]
I'm on Pop_OS! (based on Ubuntu), so GNU Coreutils comes with it. It must be the version because on my Pop_OS machine (ls version 8.32) there's no `--zero` option, but on my Arch machine (ls version is 9.5) there is.

I'm probably going to switch to a rolling release distro on my main machine next time I get a new laptop to not have to deal with outdated packages like this, this is not the first time!

**Comment by linguisticmind** [comment]
I'm on Debian Stable (12, bookworm), and I have `ls` v9.1.

**Comment by linguisticmind** [comment]
Fixed in 6093c62 ([v0.2.4](https://github.com/linguisticmind/search-in-subs/releases/tag/v0.2.4)).
